# fly.toml app configuration file generated for dsk-habits on 2023-11-19T18:42:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dsk-habits"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
