POST http://0.0.0.0:8080/users
Accept-Encoding: gzip
Content-Type: application/json

{
    "username": "username",
    "habits": [
        {
            "name": "rydde",
            "completions": [
                "2023-09-20",
                "2023-09-29",
                "2023-09-30"
            ]
        }
    ]
}

###

GET http://0.0.0.0:8080/users/1
Accept-Encoding: gzip